services:

  leantime:
    image: leantime/leantime:latest
    container_name: ${COMPOSE_PROJECT_NAME}_leantime
    restart: always
    environment:
      LEAN_DB_HOST: mysql
      LEAN_DB_USER: ${LEAN_DB_USER}
      LEAN_DB_PASSWORD: ${LEAN_DB_PASSWORD}
      LEAN_DB_DATABASE: ${LEAN_DB_DATABASE}
      LEAN_DB_PORT: ${LEAN_DB_PORT}
      LEAN_APP_URL: http://localhost:${LEAN_PORT}
      LEAN_DEFAULT_TIMEZONE: ${LEAN_DEFAULT_TIMEZONE}
      LEAN_SESSION_PASSWORD: LEAN_SESSION_PASSWORD
    ports:
     - "${LEAN_PORT}:8080"
    volumes:
     - ${LEANTIME_DATA_PATH}/storage:/var/www/html/storage
     - ${LEANTIME_DATA_PATH}/userfiles:/var/www/html/userfiles
     - ${LEANTIME_DATA_PATH}/public_userfiles:/var/www/html/public/userfiles
     - ${LEANTIME_DATA_PATH}/plugins:/var/www/html/app/Plugins
    networks:
     - external_network

networks:
  external_network:
    name: ${NETWORK_NAME}
    external: true
