services:

  mysql:
    image: mysql:latest
    container_name: ${COMPOSE_PROJECT_NAME}_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
     - "${MYSQL_PORT}:3306"
    volumes:
     - ${MYSQL_DATA_PATH}:/var/lib/mysql
    networks:
     - external_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: ${COMPOSE_PROJECT_NAME}_phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    ports:
     - "${PHPMYADMIN_PORT}:80"
    depends_on:
     - mysql
    networks:
     - external_network

networks:
  external_network:
    name: ${NETWORK_NAME}
    external: true
